development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  url: redis://animals-chat-react.herokuapp.com/ #<%= ENV.fetch("REDIS_URL") { "http://localhost:3000" } %> # redis://localhost:6379/1 http://animals-chat-react.herokuapp.com/
  channel_prefix: Chat_API_production
